version: '3.7'

services:
  activity:
    build:
      context: ./services/activity
      dockerfile: Dockerfile
    volumes:
      - './services/activity:/usr/src/app'
    ports:
      - 5001:5000
    env_file:
      - ./services/activity/.env
    depends_on:
      - activity-db
    secrets:
      - activity-db_python_password

  activity-db:
    build:
      context: ./services/activity-db
      dockerfile: Dockerfile
    restart: always
    expose:
      - 27017
    # for debugging on host (dev only)
    ports:
      - 27017:27017
    env_file:
      - ./services/activity-db/.env
    volumes:
      - activity-db_data:/data/db
    secrets:
      - activity-db_python_password
      - activity-db_root_password

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - activity

volumes:
  activity-db_data:

secrets:
  activity-db_python_password:
    file: secrets/activity-db_python_password.txt
  activity-db_root_password:
    file: secrets/activity-db_root_password.txt
