version: '3.7'

services:
  activity:
    build:
      args:
        env: prod
    entrypoint:
      - gunicorn 
      - -b 
      - 0.0.0.0:5000
      - manage:app
    env_file:
      - ./.env.d/prod.env
