version: '3.7'

services:
  activity:
    build:
      args:
        env: dev
    entrypoint:
      - python 
      - manage.py
      - run
      - -h
      - 0.0.0.0
    env_file:
      - ./.env.d/dev.env
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
