version: '3.7'

services:
  activity:
    build:
      args:
        env: prod
    entrypoint:
      - gunicorn 
      - -b 
      - 0.0.0.0:5000
      - manage:app
    env_file:
      - ./.env.d/prod.env
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - activity

