version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    env_file:
      - ./.env.d/common.env
    depends_on:
      - db
    secrets:
      - db_application_password

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    expose:
      - 27017
    env_file:
      - ./db/.env.d/test.env
    secrets:
      - db_application_password
      - db_root_password

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_application_password:
    file: ./secrets/db_application_password.txt
